### ISSUE TITLE
SessionTerminated event is not received while socket is connected

### ISSUE THREAD

**Issue by ericlu88** [bloomberg/blpapi-http#39]
When a socket is connected and I kill the underlying `blpSession`, I did not received a `SessionTerminated` events. The event is received if there's no socket connected.

**Comment by ericvw** [comment]
After #44 let's start addressing

**Comment by ericvw** [comment]
I am seeing the event being emitted, but something isn't properly handing some error and propagating the the termination to the user of the `blpapi-wrapper`:

``` bash
events.js:85
      throw er; // Unhandled 'error' event
            ^
Error: session terminated
    at Object._.cleanupFn (/Users/eric/projects/blpapi-http/lib/blpapi-wrapper.js:176:50)
    at /Users/eric/projects/blpapi-http/lib/blpapi-wrapper.js:179:23
    at Array.forEach (native)
    at /Users/eric/projects/blpapi-http/lib/blpapi-wrapper.js:178:59
    at Function.forEach (/Users/eric/projects/blpapi-http/node_modules/lodash/dist/lodash.js:3297:15)
    at lodash.ctor.(anonymous function) [as forEach] (/Users/eric/projects/blpapi-http/node_modules/lodash/dist/lodash.js:5924:31)
    at Session.sessionTerminatedHandler (/Users/eric/projects/blpapi-http/lib/blpapi-wrapper.js:177:15)
    at g (events.js:199:16)
    at emit (events.js:107:17)
    at session.emit (/Users/eric/projects/blpapi-http/node_modules/blpapi/blpapi.js:10:19)
```

Digging into this further.
